spring:
  cloud:
    gateway:
      routes:
        - id: msvc-bancos
          uri: lb://msvc-bancos
          predicates:
            - Path=/api/bancos/**
          filters:
            - StripPrefix=2
        - id: msvc-usuarios
          uri: lb://msvc-usuarios
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=2