apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8001"
  db_host: "mysql8:3306"
  database: "msvc_usuarios"
#  username: "root"
#  password: "123"
  banco_url: "msvc-bancos:8002"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-bancos
data:
  port: "8002"
  db_host: "postgres14:5432"
  database: "msvc_bancos"
#  username: "postgres"
#  password: "1234"
  usuario_url: "msvc-usuarios:8001"