apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-bancos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-bancos
  template:
    metadata:
      labels:
        app: msvc-bancos
    spec:
      containers:
        - name: bancos
          image: jaredsantiag/bancos:latest
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              value: "8002"
            - name: DB_HOST
              value: "postgres14:5432"
            - name: DB_DATABASE
              value: msvc_bancos
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: "1234"
            - name: USUARIOS_URL
              value: "msvc-usuarios:8001"