apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-bancos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-bancos
  template:
    metadata:
      labels:
        app: msvc-bancos
    spec:
      containers:
        - name: bancos
          image: jaredsantiag/bancos:latest
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: msvc-bancos
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: msvc-bancos
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: msvc-bancos
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: msvc-bancos
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: msvc-bancos
                  key: password
            - name: USUARIOS_URL
              valueFrom:
                configMapKeyRef:
                  name: msvc-bancos
                  key: usuario_url