version: "3.9"
services:
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: msvc_bancos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  msvc-bancos:
    container_name: msvc-bancos
    image: jaredsantiag/bancos
#    build:
#      context: ./
#      dockerfile: ./msvc-bancos/Dockerfile
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: postgres14:5432
      DB_DATABASE: msvc_bancos
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      USUARIOS_URL: ec2-3-83-83-183.compute-1.amazonaws.com:8001
    networks:
      - spring
    depends_on:
      - postgres14
      - msvc-usuarios
    restart: always

volumes:
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring